### ISSUE TITLE
Question: Sitemesh 2 vs 3?

### ISSUE THREAD

**Issue by supsup** [sitemesh/sitemesh2#40]
Noticed  Sitemesh 2/3 has become active again. 
What is the suggested path for new users of sitemesh: 2 or 3?

What caused the project to become active again?

Just Curious.

**Comment by codeconsole** [comment]
I would recommend Sitemesh 3 due to its simplicity.  It works well with any templating engine and no customization is needed.  See the [Spring Boot example](https://github.com/sitemesh/sitemesh3/tree/master/sitemesh-examples-springboot)

However, there are frameworks still heavily dependent on Sitemesh 2 so the plan is to continue to maintain it.

I've used both Sitemesh 2 and Sitemesh 3 on a few fairly large projects for over 10 years. 

Pull requests are welcome on either  :)
We plan on being more proactive on resolving outstanding issues for both projects.
